export { default as Trending } from "./Trending";
export { default as Latest } from "./Latest";
export { default as Genres } from "./Genres";
export { default as Upcoming } from "./Upcoming";
export { default as Popular } from "./Popular";
export { default as AnimeDetails } from "./AnimeDetails";
export { default as WatchAnime } from "./WatchAnime";
export { default as WatchAnimeDetail } from "./WatchAnimeDetail";
export { default as FilterAnime } from "./FilterAnime";
