export { default as Trending } from "./Trending";
export { default as Latest } from "./Latest";
export { default as Genres } from "./Genres";
export { default as TopAiring } from "./TopAiring";
export { default as Dub } from "./Dub";
export { default as AnimeDetails } from "./AnimeDetails";
export { default as WatchAnime } from "./WatchAnime";
export { default as WatchAnimeDetail } from "./WatchAnimeDetail";
export { default as FilterAnime } from "./FilterAnime";
